Repository KnapsackPro/knapsack_pro-ruby, pull requests merged in 2023-08, with the labels that each got.

#214 Handle exception when running rspec (Queue mode)
  lib/knapsack_pro/formatters/rspec_queue_summary_formatter.rb
  lib/knapsack_pro/runners/queue/rspec_runner.rb
  lib/knapsack_pro/tracker.rb
  spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
Labels: bug

#215 Handle RSpec exceptions when running RSpec in Queue mode (improvements)
  lib/knapsack_pro/runners/queue/rspec_runner.rb
  spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
  spec/knapsack_pro/tracker_spec.rb
Labels: bug, enhancement

#221 Detect user seats for AppVeyor, Codefresh, Codeship
  CHANGELOG.md
  lib/knapsack_pro/config/ci/app_veyor.rb
  lib/knapsack_pro/config/ci/cirrus_ci.rb
  lib/knapsack_pro/config/ci/codefresh.rb
  lib/knapsack_pro/config/ci/codeship.rb
  lib/knapsack_pro/config/ci/heroku.rb
  lib/knapsack_pro/config/ci/semaphore.rb
  lib/knapsack_pro/config/ci/semaphore2.rb
  lib/knapsack_pro/config/ci/travis.rb
  spec/knapsack_pro/config/ci/app_veyor_spec.rb
  spec/knapsack_pro/config/ci/codefresh_spec.rb
  spec/knapsack_pro/config/ci/codeship_spec.rb
Labels: enhancement

#222 Enforce `frozen_string_literal: true` in the gem files with Rubocop
  .circleci/config.yml
Labels: enhancement
